/*
 * Copyright (c) 2001-2002 by Fuji Xerox Co., Ltd. All rights reserved.
 *
 * $Id: jbf2_error.h,v 1.4 2009/12/22 08:11:17 chikyu Exp $
 */

#ifndef JBF2_ERROR_H
#define JBF2_ERROR_H

#define JBF2_ERRNO(x) ((JBF2Errno)(x))
typedef struct _JBF2Error JBF2Error;

typedef enum {
	JBF2_ERROR_NONE,
	JBF2_ERROR_FATAL,
	JBF2_ERROR_CANNOT_PUTBACK,
	JBF2_ERROR_UNKNOWN_OPERATOR,
	JBF2_ERROR_MMR_UNKNOWN_MODE,
	JBF2_ERROR_MMR_LACKS_EOF,
	JBF2_ERROR_NOT_JBIG2,
	JBF2_ERROR_BAD_TABLE,
	JBF2_ERROR_OUT_OF_MEMORY,
	JBF2_ERROR_UNKNOWN_PAGE_HEIGHT,
	JBF2_ERROR_INVALID_DEPTH,
	JBF2_ERROR_UNKNOWN_SEGMENT_TYPE,
	JBF2_ERROR_BAD_REFERENCE_COUNT,
	JBF2_ERROR_INVARID_REFERENCE,
	JBF2_ERROR_NOT_IMPLEMENTED,
	JBF2_ERROR_UNKNOWN_EXTENSION,
	JBF2_ERROR_UNEXPECTED_EOF,
	JBF2_ERROR_PAGE_NOT_FOUND,
	JBF2_ERROR_SEGMENT_NOT_FOUND,
	JBF2_ERROR_REFERENCE_NOT_FOUND,
	JBF2_ERROR_SYMBOL_NOT_FOUND,
	JBF2_ERROR_PATTERN_NOT_FOUND,
	JBF2_ERROR_BITMAP_OVERRUN,
	JBF2_ERROR_TOO_MANY_EXPORT_FLAGS,
	JBF2_ERROR_USER_DEFINE = 1000
} JBF2Errno;

struct _JBF2Error {
	JBF2Errno errno_;
};

void		 jbf2_error_init	(JBF2Error *error);
JBF2Errno	 jbf2_error_get		(JBF2Error *error);
void		 jbf2_error_set		(JBF2Error *error,
					 JBF2Errno  errno_);
const char	*jbf2_error_string	(JBF2Error *error);

#endif /* JBF2_ERROR_H */

